In [1]:
import pandas as pd

r_cols = ['user_id','movie_id', 'rating']
ratings = pd.read_csv('ml-100k/u.data', sep='\t', names=r_cols, usecols=range(3))
ratings.head()

   user_id  movie_id  rating
0        0        50       5
1        0       172       5
2        0       133       1
3      196       242       3
4      186       302       3

In [3]:
import numpy as np
movieProperties = ratings.groupby('movie_id').agg({'rating': [np.size, np.mean]})
movieProperties.head()

C:\Users\Aditya\AppData\Local\Temp\ipykernel_23964\4202407435.py:2: FutureWarning: The provided callable <function mean at 0x000001FB2E8BFEC0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  movieProperties = ratings.groupby('movie_id').agg({'rating': [np.size, np.mean]})

         rating
           size      mean
movie_id
1           452  3.878319
2           131  3.206107
3            90  3.033333
4           209  3.550239
5            86  3.302326

In [6]:
# Lets split the data into train and test
import pandas as pd
from sklearn.model_selection import train_test_split

df = pd.DataFrame(movieProperties)

X = df['movie_id']
y = df['rating']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=90)

KeyError: 0